### ISSUE TITLE
laser_scan_matcherが起動していない

### ISSUE THREAD

**Issue by haganeLego** [hsr-project/tmc_wrs_docker#11]
こんにちは．
現在こちらのシミュレーターを使って開発しているのですが，docker環境起動時に以下のエラーが発生しています．

## エラーメッセージ
```
simulator_1  | setting /run_id to b18b3554-27cf-11eb-88bc-0242ac1e0003
simulator_1  | process[rosout-1]: started with pid [90]
simulator_1  | started core service [/rosout]
simulator_1  | process[gazebo-2]: started with pid [97]
simulator_1  | process[gazebo_gui-3]: started with pid [101]
simulator_1  | process[spawn_hsrb_model-4]: started with pid [144]
simulator_1  | process[ WARN] [1605505859.153237300]: The root link odom has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
simulator_1  | ERROR: cannot launch node of type [laser_scan_matcher/laser_scan_matcher_node]: laser_scan_matcher
```

最下段のエラー見たところ，そもそも laser_scan_matcher が存在していないため起動できず，自己位置推定が上手くいっていないように思えます．
READMEのインストール手順通りに環境を用意したのですが，何かしら別の手順を踏む必要があるのでしょうか？
ご確認お願いします．

**Comment by yosuke** [comment]
laser_scan_matcherの件ですが、OSS版のdockerイメージはuse_laser_odometryをfalseにして構築しています。
意図してオフにしているのにlaunch上でエラーが表示されてしまうのが気持ち悪いのですが、そのまま使ってみていただけますでしょうか？
こちらで検証した感じ自己位置推定はそこまで悪くなかったように思うのですが、もしタスクの実行に支障が出るようであれば改善を検討しますので教えてください。

**Comment by haganeLego** [comment]
下記リンクにこちらで開発している物体把持の動画を置いています．
https://www.dropbox.com/s/wri665sjtljky9u/moveit.mp4?dl=0

動画の半透明のものがMoveItでのプランニングの結果になっているのですが，プランニングと実際の動作に乖離があるため，物体把持の成功率が低くなっています．
これらの原因が自己位置が上手く補正出来ていないためと考えており，可能であればlaser_scan_matcherを立ち上げて自己位置をもっと正確に推定したいと考えおります．

**Comment by yosuke** [comment]
LRF（濃い赤い点列）とマップの重なりを見ると自己位置推定の精度がわかるのですが、ややズレているもののそんなに悪くはなさそうな感じがします。特にオブジェクトを認識したと思われるタイミング（視線を落として画像が更新される）と把持の実行の間ではそこまでズレが変化していないので、成功してもおかしくなさそうな感じです。
やや気になるのが、プランニングが実行前からズレており、なんとなくそのズレがmapとodomのズレと一致していそうな点です。プランニングのframeの設定が適切かチェックしてみていただけますでしょうか？場合によっては物体認識のframeをプランニングに合わせた方が良いかもしれません。

**Comment by haganeLego** [comment]
ご助言ありがとうございます．
まずはframeの設定を見直してみたいと思います．

**Comment by haganeLego** [comment]
こちらframeの設定見直したところ物体把持が成功するようになりました．
ありがとうございます．
