### ISSUE TITLE
重たい物体を把持できない

### ISSUE THREAD

**Issue by TomohiroOno33** [hsr-project/tmc_wrs_docker#13]
重たい物体（Pitcher Baseなど）を把持しようとすると，握り込んでも落としてしまいます．
チュートリアルにある`move_hand`や，`/hsrb/gripper_controller/apply_force/`を使ってみましたが，うまくいきませんでした．
他に良い方法があれば教えてください．

参考までに，Pitcher Baseを把持しようとしたときの動画を共有します．
（動画は`apply_force`を使ったときのものです．）
https://1drv.ms/v/s!AggoVdDLXKk3hsYUS96iR5spq_Ar8A?e=Zngsyd

**Comment by yosuke** [comment]
フィードバックありがとうございます。
この問題はこちらでも確認（Pitcher以外にもクレンザーが持てません）しており、シミュレータ側のパラメータ変更で対応したいと思っています。
具体的には、ハンドにはHSRのバネ機構を模倣するためのゆるいPIDがかかっているのですが、それを少し強く調整する予定です。
調整が完了したらアナウンスしますので、この問題については少々お待ちください。

**Comment by yosuke** [comment]
調査の結果、1.2kg以上のものは持てないようにシミュレータが書かれていることが判明。
上限を上げることもできるが、1.2kgはHSRの可搬重量と一致するよう設定されている思うので、オブジェクトの重量を軽く調整した方が良さそう（Pitcher Baseはシミュレータ上で3kgもあるので実物と比べて重すぎる＆他にも不用意に重いオブジェクトがある）。
オブジェクトの干渉形状データの法線ベクトルがおかしい問題も見つかったので、合わせて修正予定。

**Comment by yosuke** [comment]
公式のデーターシートによるとPither baseは178グラム。
http://www.ycbbenchmarks.com/wp-content/uploads/2015/09/object-list-Sheet1.pdf

**Comment by yosuke** [comment]
@TomohiroOno33 
物体の重量を全て実際の重量と同じに設定しました。
以下のコマンドを入力してシミュレータを更新してください。
```
docker-compose pull simulator
```
極端に重い物体がなくなったので、全て持てるようになったはず、と思いますが、おかしな挙動があったらまた教えてください。

**Comment by TomohiroOno33** [comment]
ご対応ありがとうございます．

`docker-compose pull simulator`

を行いましたが，Pitcher Baseの重さがシミュレータ上で3.44kgとなっており，変わってないように思います．
把持を行ったところ，以前と同様に把持できずに落としてしまいました．

**Comment by yosuke** [comment]
もしnvidia版を使っている場合は、以下のコマンドです。
```
docker-compose -f docker-compose.nvidia.yml pull simulator
```
pullしてから`docker-compose up`し直すとシミュレータが再作成されるはずなのですが、、、。

**Comment by TomohiroOno33** [comment]
nvidia版を使用していたので，上記コマンドも実行してみましたが，変わりませんでした．

`docker-compose up`，`docker-compose -f docker-compose.nvidia.yml up`
を両方共試してみましたが，どちらもだめでした．
（GazeboのGUIからmassを見ると3.44になっています）

**Comment by yosuke** [comment]
`docker-compose down`してから`docker-compose up`するとどうでしょうか？
ワークスペースがリセットされるので、追加で入れたaptパッケージなどは再インストールが必要になりますが。

**Comment by TomohiroOno33** [comment]
```sh
$ docker-compose down
$ docker-compose up
```
の手順で，変更を確認できました．
ありがとうございます！
