### ISSUE TITLE
Task2における運搬物体の指定に関して

### ISSUE THREAD

**Issue by ItoMasaki** [hsr-project/tmc_wrs_docker#15]
[ロボットを持っていなくても無料で参加できるロボカップ](https://qiita.com/yosuke@github/items/17842508579b3561f048#task2)を読む限りでは物体の指定は/messageトピックでpublishされるということですが型に関してはstd_msgsのStringで問題ないでしょうか?
また他のIssueではROOM2の移動したタイミングで命令が来るという記載がありますが, rostopic echo /message でメッセージを監視しましたが, 送られている様子は伺えませんでした.
ROOM2に移動する以外にも条件がある場合は教えていただければ幸いです.

**Comment by yosuke** [comment]
実装が間に合っておらず、、、でお待たせしてしまいすいませんでした。
実装を追加しましたので、docker-compse pullしてシミュレータを更新してテストしてみてください。
得点計算部分がまだ間に合っておらずで、少なくとももう１回更新します。

**Comment by yosuke** [comment]
データ型、トピック名、タイミングの理解はその理解であっています。シミュレータがうまく動かない場合は、教えてください。

**Comment by ItoMasaki** [comment]
ご連絡ありがとうございます.

先ほど docker-compose pull を行ったましたが, 以下のエラーが起きました.
```
Pulling xserver   ... done
Pulling simulator ... waiting
Pulling workspace ... done
ERROR: for simulator  error pulling image configuration: Get https://ghcr.io/v2/hsr-project/tmc_wrs_docker/blobs/sha256:8c7f9671b27b701e914d066aeb52ededc0dae0a9d9c07e3d281f3cab7b5851d5: EOF
ERROR: error pulling image configuration: Get https://ghcr.io/v2/hsr-project/tmc_wrs_docker/blobs/sha256:8c7f9671b27b701e914d066aeb52ededc0dae0a9d9c07e3d281f3cab7b5851d5: EOF
```
そのためか, いまだに /message トピックに把持対象の物体名がpublishされていません.
`rostopic echo /message`でも確認しましたが, publishされていませんでした.

確認のほどよろしくお願いします.

**Comment by yosuke** [comment]
エラーログから見るとghcr.io（githubのdocker repositoryサービス）のサービス遅延のような症状です。
こちらでも試しにpullしてみたのですが、エラーは出ないもののいつもに比べてかなりダウンロード速度が遅い状況で、障害が発生しているのかもしれません。
時間をおけば解消されると思うので、少し待ってからリトライしてみてください。

**Comment by ItoMasaki** [comment]
返信ありがとうございます.

`docker-compose pull`を行った上で, プログラムを走らせたところ /message に運搬物体がpublishされることが確認できました.
対応ありがとうございました.

また`docker-compose -f docker-compose.nvidia.yml pull`では以下のようなエラーが起きました.
```
Pulling xserver   ... done
Pulling simulator ... error
Pulling workspace ... done
ERROR: for simulator  Get https://ghcr.io/v2/hsr-project/tmc_wrs_docker/manifests/nvidia: EOF
ERROR: Get https://ghcr.io/v2/hsr-project/tmc_wrs_docker/manifests/nvidia: EOF
```
こちらに関しても同様に時間を置いてから再度コマンドを走らせれば解決しますでしょうか?

よろしくお願いします.

**Comment by ItoMasaki** [comment]
上記の問題は解決しました. ありがとうございます.

**Comment by yosuke** [comment]
了解しました。報告ありがとうございます。
