### ISSUE TITLE
採点サーバーについて

### ISSUE THREAD

**Issue by akaitatitatisann** [hsr-project/tmc_wrs_docker#16]
launchで使用するパッケージをすべて指定のレポジトリにいれ、dockerfileにそのレポジトリ内をコピーする処理をいれ、採点サーバーにpushしましたが、launchがないとの結果が送られてきます。ちなみにですが、同じdockerfileをローカルで実行すると動くので、gitに上げる際、ローカルでのdockerfileの書き方とは異なる点などあるのでしょうか？

**Comment by yosuke** [comment]
サーバ側のエラーログを見てみたのですが、ログではよくわかりませんでした。
利用したDockerfileの内容をこのissueに貼り付けてもらうことは可能でしょうか？
勝負に関連する部分は消して隠してもらっても構いません。

**Comment by yosuke** [comment]
可能性としてあり得るのが、サンプルのDockerfileではパッケージをインストールしてからlaunchしているので、その場合は、CMakeLists.txtに以下のインストール設定が必要です。
https://github.com/devrt/wrs2020-robocup-challenge/blob/main/wrs_challenge/CMakeLists.txt#L15

ただ、ローカルで同じDockerfileを実行すると動く、とのことでしたので、違う理由かもしれません。

**Comment by akaitatitatisann** [comment]
FROM sobits/robocup_dpsl_sim_basic

SHELL [ "/bin/bash", "-c" ]

# install depending packages (install moveit! algorithms on the workspace side, since moveit-commander loads it from the workspace)
# install bio_ik
# update & upgrade for install depending packages
RUN apt-get update && \
    apt-get upgrade -y

# install packages
RUN apt-get install -y \
    git \
    curl \
    ros-$ROS_DISTRO-amcl \
    ros-$ROS_DISTRO-map-server \
    ros-$ROS_DISTRO-move-base \
    ros-$ROS_DISTRO-pcl-conversions \
    ros-$ROS_DISTRO-pcl-ros

    # update & upgrade
RUN apt-get update &&\
    apt-get -y upgrade &&\
    apt-get clean && \
    apt-get autoremove

# create workspace folder
RUN mkdir -p /workspace/src

# copy our algorithm to workspace folder
ADD . /workspace/src

RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    cd /workspace && \
    catkin_init_workspace && \
    catkin_make install -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/ros/$ROS_DISTRO -DCATKIN_ENABLE_TESTING=0

# install dependencies defined in package.xml
RUN cd /workspace && /ros_entrypoint.sh rosdep install --from-paths src --ignore-src -r -y

# compile and install our algorithm
RUN cd /workspace && /ros_entrypoint.sh catkin_make install -DCMAKE_INSTALL_PREFIX=/opt/ros/$ROS_DISTRO

RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    source workspace/devel/setup.bash && \
    echo "export ROS_MASTER_URI=http://simulator:11311/" >> ~/.bashrc &&\
    echo "source ./devel/setup.bash" >> ~/.bashrc &&\
    source ~/.bashrc

CMD roslaunch hsr_navigation try_move.launch

**Comment by akaitatitatisann** [comment]
[test.txt](https://github.com/hsr-project/tmc_wrs_docker/files/5650566/test.txt)
よろしくお願いいたします。

**Comment by yosuke** [comment]
ローカルでは`source workspace/devel/setup.bash`しているのでhsr_navigationパッケージのlaunchfileが見つかるのですが、それが/opt/rosにインストールされていないのが問題な気がします。
hsr_navigationパッケージのCMakeLists.txtに以下のようなinstall命令は書かれているでしょうか？
https://github.com/devrt/wrs2020-robocup-challenge/blob/main/wrs_challenge/CMakeLists.txt#L15

**Comment by akaitatitatisann** [comment]
ありがとうございます。

**Comment by akaitatitatisann** [comment]
ありがとうございます。
試してみたところ、CMakeList.txtのご指摘いただいた記述の欠損と、
export ROS_PACKAGE_PATH=/workspace/src:$ROS_PACKAGE_PATH
の一行をdockerfileに追加することで解決しました。
