### ISSUE TITLE
採点サーバーでpythonスクリプトに実行権限をつけるための手順

### ISSUE THREAD

**Issue by OITYukiInoue** [hsr-project/tmc_wrs_docker#19]
お世話になります。
現在採点サーバーにコードをプッシュする練習中ですが、

```
ERROR: cannot launch node of type [wrs_challenge/somecode.py]: Cannot locate node of type [somecode.py] in package [wrs_challenge]. Make sure file exists in package path and permission is set to executable (chmod +x)
```
となります。Dockerファイルでモードを変えるスクリプトを実行してみていますが好転しません。どのタイミングで
どんなスクリプトを入れたらいいでしょうか。

[set755.sh.txt](https://github.com/hsr-project/tmc_wrs_docker/files/5686259/set755.sh.txt)
[Dockerfile.txt](https://github.com/hsr-project/tmc_wrs_docker/files/5686261/Dockerfile.txt)

**Comment by OITYukiInoue** [comment]
自己解決したようなので報告します。ケアレスミスですが、
CMakeLists.txtへのコード追加が抜けておりました。実行エラーからはファイルがコピーされていないのか、実行権限がないのかがちょっとわかりにくいことから、間違いに気が付きませんでした。以上です。

**Comment by yosuke** [comment]
ありがとうございます。ちょうどその問題かなと書こうとしたところでした。
CMakeLists.txtへの記述でスクリプトのコピーと実行権限の付与の両方が行われます。

**Comment by OITYukiInoue** [comment]
お世になります

issue はclose でおいします


井上雄o　大阪工I大学　ロボティクス＆デザイン工学部

Yuki Inoue　Osaka Institute of Technology

yuki.inoue@oit.ac.jp

tel 06-6147-7685 fax 06-6147-6513

070-50424960 (mobile)

________________________________
差出人: Yosuke Matsusaka <notifications@github.com>
送信日r: 2020年12月14日 14:05
宛先: hsr-project/tmc_wrs_docker <tmc_wrs_docker@noreply.github.com>
CC: Yuki Inoue <yuki.inoue@oit.ac.jp>; Author <author@noreply.github.com>
件名: Re: [hsr-project/tmc_wrs_docker] 竦悭旦`バ`でpythonスクリプトにg行叵蓼颏膜堡毪郡幛问猪 (#19)


ありがとうございます。ちょうどその}かなと长Δ趣筏郡趣长恧扦筏俊
CMakeLists.txtへの述でスクリプトのコピ`とg行叵蓼胃队毪I方が行われます。

―
