### ISSUE TITLE
採点用サーバーにおけるのcudaのバージョンについて

### ISSUE THREAD

**Issue by KoichiSasano** [hsr-project/tmc_wrs_docker#20]
物体認識をyoloを使って行っているのですが、先日採点用サーバーにpushしたところ
うまく動作しませんでした。
HostPCではうまく動作したので、採点用サーバーとのcuda等々のバージョンの違いが原因ではないかと考えています。

HostPCのスペックは、
・Ubuntu：18.04LTS
・nvidia-driver：455.45.01
・CUDA：10.1
・cuDNN：v7.6.5
となっております。

また、採点用サーバーのcudaやcupyのバージョンはこちらが指定することは可能でしょうか。
ご確認、よろしくお願いいたします。

**Comment by yosuke** [comment]
採点サーバではCUDA11が動いているのですが、それ以下のバージョンであれば問題なく動くはずです。
Dockerfileに以下の各行が必要ですが、書かれているでしょうか？
```
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
```

**Comment by yosuke** [comment]
cudaやcupyについては、Dockerfileを編集して自分でインストールする形になります。
このあたりが参考になると思います。
https://github.com/hsr-project/tmc_wrs_docker/blob/master/Dockerfile.nvidia#L8-L22

**Comment by KoichiSasano** [comment]
ありがとうございます。
提示して頂いた通りにDockerfileを作成したのですが、以下のようなエラーがでてしまいました。
物体認識にはchainer v6.0.0を用いております。

`RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).CuPy is not correctly installed.
If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze
If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv
Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html
`
重ねて質問させていただきたいのですが、
現在採点用サーバーにて複数のノードを起動すると
結果が帰ってくるまでに１５分以上かかってしまいます。より早く結果を返すことはできるでしょうか。

**Comment by yosuke** [comment]
Dockerfileの該当部分（cudaとcupyのインストール部分）を貼り付けていただけますでしょうか？
おそらく今はシミュレーションの強制タイムアウト（シミュレーション時間で20分強＝実時間で18分ぐらい）までプロセスが動き続けてタイムアウトしてようやく返ってくるという感じになっているのではないかと思います。エラーが出た場合にプロセスを終了させるようにプログラムを書けばもっと早く結果が返ります。

**Comment by KoichiSasano** [comment]
返信ありがとうございます。
該当の部分は、以下のとおりです。
`
###################################
# Environment_variable_preference #
###################################
ENV CUDA_VERSION 10.1.105
ENV CUDA_PKG_VERSION 10-1=$CUDA_VERSION-1
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility,graphics
ENV NVIDIA_REQUIRE_CUDA "cuda>=10.1 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419"
ENV NCCL_VERSION 2.4.8
ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs
ENV CUDNN_VERSION 7.6.5.32

# install packages
RUN apt-get install -y curl 

# nvidia driver setting 
## base ##
RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg2 curl ca-certificates && \
    curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add - && \
    echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

# For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-cudart-$CUDA_PKG_VERSION \
    cuda-compat-10-1 \
    && ln -s cuda-10.1 /usr/local/cuda

# Required for nvidia-docker v1
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

## runtime ##
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-libraries-$CUDA_PKG_VERSION \
    cuda-npp-$CUDA_PKG_VERSION \
    cuda-nvtx-$CUDA_PKG_VERSION \
    libcublas10=10.2.1.243-1 \
    libnccl2=$NCCL_VERSION-1+cuda10.1 \
    && apt-mark hold libnccl2

# apt from auto upgrading the cublas package. See https://gitlab.com/nvidia/container-images/cuda/-/issues/88
RUN apt-mark hold libcublas10

## devel ##
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-nvml-dev-$CUDA_PKG_VERSION \
    cuda-command-line-tools-$CUDA_PKG_VERSION \
    cuda-nvprof-$CUDA_PKG_VERSION \
    cuda-npp-dev-$CUDA_PKG_VERSION \
    cuda-libraries-dev-$CUDA_PKG_VERSION \
    cuda-minimal-build-$CUDA_PKG_VERSION \
    libcublas-dev=10.2.1.243-1 \
    libnccl-dev=2.4.8-1+cuda10.1 \
    && apt-mark hold libnccl-dev

# apt from auto upgrading the cublas package. See https://gitlab.com/nvidia/container-images/cuda/-/issues/88
RUN apt-mark hold libcublas-dev

## devel/cudnn7 ##
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    libcudnn7=$CUDNN_VERSION-1+cuda10.1 \
    libcudnn7-dev=$CUDNN_VERSION-1+cuda10.1 \
    && apt-mark hold libcudnn7

#install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python2 get-pip.py && \
    rm get-pip.py && \
    pip install -U pip

#install cupy and chainer
RUN source ~/.bashrc &&\
    pip install -U cupy-cuda101==6.0.0 \
    chainer==6.0.0 \
    chainercv

`
update/upgrade, autoremoveなどの部分は省略しております。
よろしくお願いいたします。

**Comment by yosuke** [comment]
試しに動かしてみたのですが、確かにエラーが出ますね、、、。
https://github.com/yosuke/test-cupy/commit/4ea471a5013a57efc4111f86a7b1beaedd3122c9

再現したのでサーバ側を改良してみます（ローカルのnvidia-dockerだと動くのでDockefileが悪いわけでは無さそうです）。

**Comment by yosuke** [comment]
nvidia/cudaイメージを使ってnvidia-smiを実行するところまでは動く。
https://github.com/yosuke/test-cupy/commit/680f73ec290a43b877ece3ac95d096ec89be79e4

**Comment by yosuke** [comment]
cupyは公式Dockerイメージを使ってもだめ
https://github.com/yosuke/test-cupy/commit/415e413d31d4f1c2cc2b45e8bb73bf3fff299a11

**Comment by yosuke** [comment]
関連するかもしれない情報
https://qiita.com/tymob/items/f706b39f5a008831cfcf

**Comment by yosuke** [comment]
この解決法が一番きれいな気がする。
https://github.com/Kaggle/docker-python/issues/361#issuecomment-448093930

**Comment by yosuke** [comment]
@KoichiSasano 
こちらのテストでは無事に動きました。サーバ側のnvidia-dockerでcompute capabilityの追加が必要だったようです。
もう動くと思うので試してみてください。
https://github.com/yosuke/test-cupy/commit/ac5220f0600335ecfd93ccc1b99ba77d9d970247

**Comment by KoichiSasano** [comment]
ありがとうございます。
試してみたところ、おそらくうまく行ってるとは思うのですが、採点の結果がdockerfileのbuild successだけ返ってきて、その後の実行できたどうかが返ってこない状況です。
この状況が何を意味しているのか教えていただきたいです。
何度も対応していただき本当にありがとうございます。

**Comment by yosuke** [comment]
採点サーバ上ではシミュレーション時間上で20分で競技がタイムアウトして競技が終了するはずなのですが、そのタイムアウト後のアルゴリズムの強制終了がうまくできていない症状です。
こちらの方でも調整してみます。

**Comment by yosuke** [comment]
タイムアウト時の挙動を調整してみました。
まだうまくいかないなどあったら、こちらに書き込んで教えてください。

**Comment by KoichiSasano** [comment]
返信ありがとうございます。
先ほど確認したところ、無事想定通りの結果が出力されました！

これにて、closeとさせていただきます。
