### ISSUE TITLE
エラー

### ISSUE THREAD

**Issue by gundam1979** [hsr-project/tmc_wrs_docker#24]
お世話になっております．
utils.py 中の
hole_body = moveit_commander.MoveGroupCommander("whole_body_light")
を実行すると，以下のメッセージが出て，処理が止まります．
よろしくお願い致します．

[ INFO] [1611242861.084445207]: Loading robot model 'hsrb'...
[ WARN] [1611242861.085229990]: Skipping virtual joint 'world_joint' because its child frame 'base_footprint' does not match the URDF frame 'odom'
[ INFO] [1611242861.085325307]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1611242861.152440956]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/robot_description_kinematics/arm/kinematics_solver_attempts' from your configuration.

**Comment by mx0c** [comment]
for everyone else having this issue just click on the play button in gazebo.
