### ISSUE TITLE
ihsrb not working

### ISSUE THREAD

**Issue by lgarattoni** [hsr-project/tmc_wrs_docker#25]
I successfully installed and launched the simulator, but I cannot use the usual python api (ihsrb). When I try, I get the a KeyError: u'/hsrb/omni_base_controller/base_coordinates'.

Could you please let me know if the python interface can be used (and therefore I have an issue on my side) or we should use another api?

**Comment by yuka-hashiguchi** [comment]
Hi @lgarattoni ,
We are sorry but ihsrb is only for HSR community members.
By default, it doesn't include ihsrb in this OSS simulator.

**Comment by lgarattoni** [comment]
I see, thank you @yuka-hashiguchi for your quick reply.
