### ISSUE TITLE
Qiita「ロボットを持っていなくても無料で参加できるロボカップ」を見ました

### ISSUE THREAD

**Issue by gundam1979** [hsr-project/tmc_wrs_docker#8]
アルゴリズムのランキングが毎週発表されます（このランキングはあくまで参考です）と書かれていましたが，どこで発表されるのでしょうか？
ランキングは，ロボカップに参加登録していなくても発表されるのでしょうか？
ロボカップ終了後でも毎週ランキングが発表されるのでしょうか？

**Comment by yosuke** [comment]
git pushするとcommit commentとして採点結果が通知されます（通知の際にメールも送信されます）。
ランキングにはロボカップに参加登録していなくても参加できます。ただ、今回はロボカップにほとんどの人が無料で参加できますので、登録して公式記録として認定してもらった方が楽しいと思います。
ロボカップ終了後も採点は継続する予定です。
