### ISSUE TITLE
サンプルプロジェクトを実行するとエラーが出る

### ISSUE THREAD

**Issue by gundam1979** [hsr-project/tmc_wrs_docker#9]
[ERROR] [1605098943.080323268]: Robot model parameter not found! Did you remap 'robot_description'?
[FATAL] [1605098943.080817823]: Unable to construct robot model. Please make sure all needed information is on the parameter server.
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/wrs_challenge/move.py", line 9, in <module>
    import utils
  File "/opt/ros/melodic/lib/wrs_challenge/utils.py", line 158, in <module>
    whole_body = moveit_commander.MoveGroupCommander("whole_body_light")
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 52, in __init__
    self._g = _moveit_move_group_interface.MoveGroupInterface(name, robot_description, ns, wait_for_servers)
RuntimeError: Unable to construct robot model. Please make sure all needed information is on the parameter server.
================================================================================REQUIRED process [move-2] has died!
process has died [pid 53, exit code 1, cmd /opt/ros/melodic/lib/wrs_challenge/move.py __name:=move __log:=/root/.ros/log/43c6e682-241c-11eb-a1b4-0242ac110002/move-2.log].
log file: /root/.ros/log/43c6e682-241c-11eb-a1b4-0242ac110002/move-2*.log
Initiating shutdown!
================================================================================
... logging to /root/.ros/log/43c6e682-241c-11eb-a1b4-0242ac110002/roslaunch-630d42c559ac-1.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://630d42c559ac:37833/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.9

NODES
  /
    move (wrs_challenge/move.py)

auto-starting new master
process[master]: started with pid [39]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 43c6e682-241c-11eb-a1b4-0242ac110002
process[rosout-1]: started with pid [50]
started core service [/rosout]
process[move-2]: started with pid [53]
[move-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by yosuke** [comment]
`ROS_MASTER_URI=http://localhost:11311`となっているのでシミュレーションサーバに接続できていない感じですね（docker-compose upで立ち上がる開発環境を使った場合、`ROS_MASTER_URI=http://simulator:11311`となるはずです）。

環境の詳細を教えてもらえるともう少しサポートできます。

**Comment by gundam1979** [comment]
同一のPCで以下のように実行しました．

まず，シミュレータをダウンロードして，
$ docker-compose -f docker-compose.nvidia.yml up
でシミュレータを起動します．次に，
$ source ./set-rosmaster.sh
でROS_MASTER_URIの設定を行います．

サンプルプロジェクトをダウンロードして，
サンプルプロジェクト内のDockerfileをビルドし，コンテナの起動すると，
前出のエラーがでました．

よろしくお願い致します．

**Comment by yosuke** [comment]
情報ありがとうございます。
確かに、`./set-rosmaster.sh`でホストで開発する形だとサンプルがうまく動かないかもしれないです。
docker-compose upした後で、HSRシミュレータのWebIDE（ http://localhost:3001/ ）を開いて開発する形だと上手くいくと思うのですがどうでしょうか？

**Comment by gundam1979** [comment]
ご回答有難うございます．
docker-compose upした後で、jupyter notebook(http://localhost:3002)にmove.pyをコピペして実行させると，動きました．
「WebIDE（ http://localhost:3001/ ）を開いてレポジトリをcloneしてアルゴリズムを開発しましょう」と書かれていますが，WebIDE上でアルゴリズムの実行（$ roslaunch wrs_challenge run.launch のような事）はどのようにすれば良いのでしょうか（WebIDEを使ったことがありません）？

よろしくお願い致します．

**Comment by yosuke** [comment]
WebIDEのメニューから「Terminal」>「New Terminal」を選択するとターミナルが開きますので、git cloneやroslaunchはそこからしてください。
左上のファイルアイコンをクリックするとファイルマネージャとエディタが出てきます。
